---
# tasks file for joe-speedboat.devel
- name: find all task files with numeric pattern
  become: no
  find:
    paths: "{{ playbook_dir }}/"
    recurse: yes
    depth: 5
    file_type: file
    use_regex: yes
    patterns: ['.*']
  register: found_playbooks
  delegate_to: localhost
  run_once: yes
- debug: var=playbook_dir
- debug: var=found_playbooks
.
