---
# tasks file for joe-speedboat.devel
- name: find all task
  become: no
  find:
    paths: "{{ playbook_dir }}/"
    recurse: yes
    depth: 5
    file_type: file
  register: found_playbooks
  delegate_to: localhost
  run_once: yes
- debug: 
    var: playbook_dir
- debug:
    var: found_playbooks

- name: find all task
  become: no
  find:
    paths: /runner
    recurse: yes
    depth: 5
    file_type: file
    use_regex: yes
    patterns: ['.*\.yml']
  register: found_playbooks2
  delegate_to: localhost
  run_once: yes
- debug:
    var: found_playbooks2

- name: Pause for 5 minutes to build
  pause:
    minutes: 5
...
